from pydantic import BaseModel, Field

from app.schemas.parse import JobDescriptionParseResponse, ResumeParseResponse


class AnalyzeRequest(BaseModel):
    parsed_resume: ResumeParseResponse = Field(
        ...,
        description="Structured resume JSON generated by the resume parser.",
    )
    parsed_job_description: JobDescriptionParseResponse = Field(
        ...,
        description="Structured job description JSON generated by the JD parser.",
    )


class AnalyzeResponse(BaseModel):
    match_score: float = Field(..., ge=0, le=100)
    strengths: list[str]
    gaps: list[str]
    missing_keywords: list[str]
    under_emphasized_experience: list[str]
    evidence_notes: list[str]
