from pydantic import BaseModel, Field

from app.schemas.analysis import AnalyzeResponse
from app.schemas.parse import JobDescriptionParseResponse, ResumeParseResponse


class RewriteSuggestionItem(BaseModel):
    original: str
    suggested: str
    rationale: str


class RewriteRequest(BaseModel):
    parsed_resume: ResumeParseResponse = Field(
        ...,
        description="Structured resume JSON generated by the resume parser.",
    )
    parsed_job_description: JobDescriptionParseResponse = Field(
        ...,
        description="Structured job description JSON generated by the JD parser.",
    )
    gap_analysis: AnalyzeResponse = Field(
        ...,
        description="Gap analysis result generated by the analysis service.",
    )


class RewriteResponse(BaseModel):
    tailored_summary: str | None
    rewrite_suggestions: list[RewriteSuggestionItem]
